services:
  astro-webserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POCKETBASE_URL=http://192.168.18.118:8090
    image: portfolio:local
    container_name: astro-webserver
    restart: always
    networks:
      - portfolio_network

networks:
  portfolio_network:
    external: true
