services:
  astro-webserver:
    image: nginx:alpine
    container_name: astro-webserver
    restart: always
    volumes:
      - /home/nino/Portfolio:/app:ro
      - /home/nino/Portfolio/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - portfolio_net

networks:
  portfolio_net:
    external: true
